version: "2.2"
services:
  mongo:
    image: mongo
    volumes:
      - ./data/:/data/db
    ports:
      - 27017:27017
    hostname: mongodb

  node:
    # build构建 本地Dockerfile文件
    build: .
    command: npm run dev
    ports:
      - 12345:12345
    links:
      - mongo
    