version: "2.2"
services:
  # node:
  #   # build构建 本地Dockerfile文件
  #   build: .
  #   ports:
  #     - 12345:12345
  #   links:
  #     - mongo

  mongo:
    image: mongo
    volumes:
      - ./data/:/data/db
    ports:
      - 27017:27017
    hostname: mongodb
    